file_version: 1.0
gameBaseDir: ""
outputDir: ""
pig_color: RANDOM
program_version: 01.00.00a
seed: Link
add_shortcut_warps_between_dungeons: false
chest_type_matches_contents: false
damage_multiplier: 2.000000
decouple_entrances: false
instant_text_boxes: true
invert_sea_compass_x_axis: false
keylunacy: false
mix_entrance_pools: false
num_race_mode_dungeons: 4
num_starting_triforce_shards: 0
player_in_casual_clothes: false
progression_battlesquid: false
progression_big_octos_gunboats: false
progression_combat_secret_caves: false
progression_dungeons: true
progression_expensive_purchases: true
progression_eye_reef_chests: false
progression_free_gifts: true
progression_great_fairies: true
progression_island_puzzles: false
progression_long_sidequests: false
progression_mail: false
progression_minigames: false
progression_misc: true
progression_obscure: false
progression_platforms_rafts: false
progression_puzzle_secret_caves: true
progression_savage_labyrinth: false
progression_short_sidequests: false
progression_spoils_trading: false
progression_submarines: false
progression_tingle_chests: false
progression_treasure_charts: false
progression_triforce_charts: false
plandomizer: false
race_mode: false
randomize_cave_entrances: false
randomize_charts: false
randomize_door_entrances: false
randomize_dungeon_entrances: false
randomize_misc_entrances: false
randomize_starting_island: false
remove_music: false
reveal_full_sea_chart: true
skip_rematch_bosses: true
starting_hcs: 0
starting_pohs: 0
starting_gear: 
  - ProgressiveShield
  - BalladOfGales
  - SongOfPassing
  - ProgressiveMagicMeter
  - ProgressiveSail
sword_mode: StartWithSword
workingDir: ""
