name: Build Latest - Wii U

on: workflow_call

env:
  SOURCE_DIR: ${{ github.workspace }}
  BUILD_TYPE: Debug

jobs:
  build-wiiu-homebrew-application:
    name: Build Wii U Homebrew Application
    runs-on: ubuntu-latest
    
    steps:
     - name: Checkout Repository
       uses: actions/checkout@v3
       with:
         submodules: recursive
    
     - name: Build App
       working-directory: ${{github.workspace}}
       run: |
         docker build -t rando .
         docker run -i -e BUILD_TYPE=full -e CMAKE_ARGS=-DENABLE_DEBUG=True -v "$(pwd):/src" rando

     - name: Get Version
       id: get-version
       shell: pwsh
       working-directory: ${{github.workspace}}/build
       run: |
         echo "RANDO_VERSION=$(((Get-Content version.hpp | Select-String -Pattern '#define RANDOMIZER_VERSION "[0-9\.a-z]*"') -Replace '.*("[0-9\.a-z]*").*', '$1') -Replace '"', '')" >> $env:GITHUB_OUTPUT
 
     - name: Save Artifact
       uses: actions/upload-artifact@v3
       with:
         path: ${{github.workspace}}/build/wwhd_rando.wuhb
         name: wwhd_rando_${{steps.get-version.outputs.RANDO_VERSION}}.wuhb
