name: Build Latest - Windows

on: workflow_call

env:
  SOURCE_DIR: ${{ github.workspace }}
  QT_VERSION: 6.3.1
  BUILD_TYPE: Debug

jobs:
  build-desktop-application-windows:
    name: Build Desktop Application Windows
    runs-on: windows-latest

    steps:
     # Increase page size so that the compiler doesn't
     # run out of memory
     - name: Configure Pagefile
       uses: al-cheb/configure-pagefile-action@v1.3
       with:
         minimum-size: 16GB
         maximum-size: 16GB
         disk-root: "C:"

     - name: Checkout Repository
       uses: actions/checkout@v3
       with:
         submodules: recursive

     - name: Install Qt
       uses: jurplel/install-qt-action@v3.2.1
       with:
         version: ${{ env.QT_VERSION }}
         host: 'windows'
         target: 'desktop'
         arch: 'win64_mingw'
         cache: true
         cache-key-prefix: install-qt-${{env.QT_VERSION}}-action

     - name: Configure CMake
       working-directory: ${{github.workspace}}
       run: cmake gui -G "MinGW Makefiles" -B build -DGITHUB_WORKFLOW=True -DEMBED_DATA=True -DENABLE_DEBUG=True
       
     - name: Build
       working-directory: ${{github.workspace}}
       run: cmake --build build --config ${{env.BUILD_TYPE}} -j

     - name: Get Version
       id: get-version
       working-directory: ${{github.workspace}}
       run: |
         echo "RANDO_VERSION=$(((Get-Content version.hpp | Select-String -Pattern '#define RANDOMIZER_VERSION "[0-9\.a-z]*"') -Replace '.*("[0-9\.a-z]*").*', '$1') -Replace '"', '')" >> $env:GITHUB_OUTPUT
       
     - name: Call windeployqt
       working-directory: ${{github.workspace}}/build
       shell: cmd # Setting up environment vars only works properly in cmd?
       run: |
         mkdir wwhd_rando_windows_${{steps.get-version.outputs.RANDO_VERSION}}
         cp wwhd_rando.exe wwhd_rando_windows_${{steps.get-version.outputs.RANDO_VERSION}}\wwhd_rando.exe
         cp ${{github.workspace}}\..\Qt\${{ env.QT_VERSION }}\mingw_64\bin\libgcc_s_seh-1.dll wwhd_rando_windows_${{steps.get-version.outputs.RANDO_VERSION}}\libgcc_s_seh-1.dll
         cp ${{github.workspace}}\..\Qt\${{ env.QT_VERSION }}\mingw_64\bin\libstdc++-6.dll wwhd_rando_windows_${{steps.get-version.outputs.RANDO_VERSION}}\libstdc++-6.dll
         cp ${{github.workspace}}\..\Qt\${{ env.QT_VERSION }}\mingw_64\bin\libwinpthread-1.dll wwhd_rando_windows_${{steps.get-version.outputs.RANDO_VERSION}}\libwinpthread-1.dll
         ${{github.workspace}}\..\Qt\${{ env.QT_VERSION }}\mingw_64\bin\qtenv2.bat && cd ${{github.workspace}}\build\wwhd_rando_windows_${{steps.get-version.outputs.RANDO_VERSION}} && windeployqt wwhd_rando.exe --no-translations --no-system-d3d-compiler --no-opengl-sw
 
     - name: Save Artifact
       uses: actions/upload-artifact@v3
       with:
         path: ${{github.workspace}}\build\wwhd_rando_windows_${{steps.get-version.outputs.RANDO_VERSION}}
         name: wwhd_rando_windows_${{steps.get-version.outputs.RANDO_VERSION}}
