
#include "HintRegion.hpp"
#include <unordered_map>

HintRegion nameToHintRegion(const std::string& name)
{
    static std::unordered_map<std::string, HintRegion> nameHintRegionMap = {
        {"NONE", HintRegion::NONE},
        {"Mailbox", HintRegion::Mailbox},
        {"TheGreatSea", HintRegion::TheGreatSea},
        {"ForsakenFortressSector", HintRegion::ForsakenFortressSector},
        {"StarIsland", HintRegion::StarIsland},
        {"NorthernFairyIsland", HintRegion::NorthernFairyIsland},
        {"GaleIsle", HintRegion::GaleIsle},
        {"CrescentMoonIsland", HintRegion::CrescentMoonIsland},
        {"SevenStarIsles", HintRegion::SevenStarIsles},
        {"OverlookIsland", HintRegion::OverlookIsland},
        {"FourEyeReef", HintRegion::FourEyeReef},
        {"MotherAndChildIsles", HintRegion::MotherAndChildIsles},
        {"SpectacleIsland", HintRegion::SpectacleIsland},
        {"WindfallIsland", HintRegion::WindfallIsland},
        {"PawprintIsle", HintRegion::PawprintIsle},
        {"DragonRoostIsland", HintRegion::DragonRoostIsland},
        {"FlightControlPlatform", HintRegion::FlightControlPlatform},
        {"WesternFairyIsland", HintRegion::WesternFairyIsland},
        {"RockSpireIsle", HintRegion::RockSpireIsle},
        {"TingleIsland", HintRegion::TingleIsland},
        {"NorthernTriangleIsland", HintRegion::NorthernTriangleIsland},
        {"EasternFairyIsland", HintRegion::EasternFairyIsland},
        {"FireMountain", HintRegion::FireMountain},
        {"StarBeltArchipelago", HintRegion::StarBeltArchipelago},
        {"ThreeEyeReef", HintRegion::ThreeEyeReef},
        {"GreatfishIsle", HintRegion::GreatfishIsle},
        {"CyclopsReef", HintRegion::CyclopsReef},
        {"SixEyeReef", HintRegion::SixEyeReef},
        {"TotGSector", HintRegion::TotGSector},
        {"EasternTriangleIsland", HintRegion::EasternTriangleIsland},
        {"ThornedFairyIsland", HintRegion::ThornedFairyIsland},
        {"NeedleRockIsle", HintRegion::NeedleRockIsle},
        {"IsletOfSteel", HintRegion::IsletOfSteel},
        {"StoneWatcherIsland", HintRegion::StoneWatcherIsland},
        {"SouthernTriangleIsland", HintRegion::SouthernTriangleIsland},
        {"PrivateOasis", HintRegion::PrivateOasis},
        {"BombIsland", HintRegion::BombIsland},
        {"BirdsPeakRock", HintRegion::BirdsPeakRock},
        {"DiamondSteppeIsland", HintRegion::DiamondSteppeIsland},
        {"FiveEyeReef", HintRegion::FiveEyeReef},
        {"SharkIsland", HintRegion::SharkIsland},
        {"SouthernFairyIsland", HintRegion::SouthernFairyIsland},
        {"IceRingIsle", HintRegion::IceRingIsle},
        {"ForestHaven", HintRegion::ForestHaven},
        {"CliffPlateauIsles", HintRegion::CliffPlateauIsles},
        {"HorseshoeIsle", HintRegion::HorseshoeIsle},
        {"OutsetIsland", HintRegion::OutsetIsland},
        {"HeadstoneIsland", HintRegion::HeadstoneIsland},
        {"TwoEyeReef", HintRegion::TwoEyeReef},
        {"AngularIsles", HintRegion::AngularIsles},
        {"BoatingCourse", HintRegion::BoatingCourse},
        {"FiveStarIsles", HintRegion::FiveStarIsles},
        {"GhostShip", HintRegion::GhostShip},
        {"DragonRoostCavern", HintRegion::DragonRoostCavern},
        {"ForbiddenWoods", HintRegion::ForbiddenWoods},
        {"TowerOfTheGods", HintRegion::TowerOfTheGods},
        {"ForsakenFortress", HintRegion::ForsakenFortress},
        {"EarthTemple", HintRegion::EarthTemple},
        {"WindTemple", HintRegion::WindTemple},
        {"Hyrule", HintRegion::Hyrule},
        {"GanonsTower", HintRegion::GanonsTower},
    };

    if (nameHintRegionMap.count(name) == 0)
    {
        return HintRegion::INVALID;
    }
    return nameHintRegionMap.at(name);
}

std::string hintRegionToName(const HintRegion& hintRegion)
{
    static std::unordered_map<HintRegion, std::string> hintRegionNameMap = {
        {HintRegion::NONE, "NONE"},
        {HintRegion::Mailbox, "Mailbox"},
        {HintRegion::TheGreatSea, "THeGreatSea"},
        {HintRegion::ForsakenFortressSector, "ForsakenFortressSector"},
        {HintRegion::StarIsland, "StarIsland"},
        {HintRegion::NorthernFairyIsland, "NorthernFairyIsland"},
        {HintRegion::GaleIsle, "GaleIsle"},
        {HintRegion::CrescentMoonIsland, "CrescentMoonIsland"},
        {HintRegion::SevenStarIsles, "SevenStarIsles"},
        {HintRegion::OverlookIsland, "OverlookIsland"},
        {HintRegion::FourEyeReef, "FourEyeReef"},
        {HintRegion::MotherAndChildIsles, "MotherAndChildIsles"},
        {HintRegion::SpectacleIsland, "SpectacleIsland"},
        {HintRegion::WindfallIsland, "WindfallIsland"},
        {HintRegion::PawprintIsle, "PawprintIsle"},
        {HintRegion::DragonRoostIsland, "DragonRoostIsland"},
        {HintRegion::FlightControlPlatform, "FlightControlPlatform"},
        {HintRegion::WesternFairyIsland, "WesternFairyIsland"},
        {HintRegion::RockSpireIsle, "RockSpireIsle"},
        {HintRegion::TingleIsland, "TingleIsland"},
        {HintRegion::NorthernTriangleIsland, "NorthernTriangleIsland"},
        {HintRegion::EasternFairyIsland, "EasternFairyIsland"},
        {HintRegion::FireMountain, "FireMountain"},
        {HintRegion::StarBeltArchipelago, "StarBeltArchipelago"},
        {HintRegion::ThreeEyeReef, "ThreeEyeReef"},
        {HintRegion::GreatfishIsle, "GreatfishIsle"},
        {HintRegion::CyclopsReef, "CyclopsReef"},
        {HintRegion::SixEyeReef, "SixEyeReef"},
        {HintRegion::TotGSector, "TotGSector"},
        {HintRegion::EasternTriangleIsland, "EasternTriangleIsland"},
        {HintRegion::ThornedFairyIsland, "ThornedFairyIsland"},
        {HintRegion::NeedleRockIsle, "NeedleRockIsle"},
        {HintRegion::IsletOfSteel, "IsletOfSteel"},
        {HintRegion::StoneWatcherIsland, "StoneWatcherIsland"},
        {HintRegion::SouthernTriangleIsland, "SouthernTriangleIsland"},
        {HintRegion::PrivateOasis, "PrivateOasis"},
        {HintRegion::BombIsland, "BombIsland"},
        {HintRegion::BirdsPeakRock, "BirdsPeakRock"},
        {HintRegion::DiamondSteppeIsland, "DiamondSteppeIsland"},
        {HintRegion::FiveEyeReef, "FiveEyeReef"},
        {HintRegion::SharkIsland, "SharkIsland"},
        {HintRegion::SouthernFairyIsland, "SouthernFairyIsland"},
        {HintRegion::IceRingIsle, "IceRingIsle"},
        {HintRegion::ForestHaven, "ForestHaven"},
        {HintRegion::CliffPlateauIsles, "CliffPlateauIsles"},
        {HintRegion::HorseshoeIsle, "HorseshoeIsle"},
        {HintRegion::OutsetIsland, "OutsetIsland"},
        {HintRegion::HeadstoneIsland, "HeadstoneIsland"},
        {HintRegion::TwoEyeReef, "TwoEyeReef"},
        {HintRegion::AngularIsles, "AngularIsles"},
        {HintRegion::BoatingCourse, "BoatingCourse"},
        {HintRegion::FiveStarIsles, "FiveStarIsles"},
        {HintRegion::GhostShip, "GhostShip"},
        {HintRegion::DragonRoostCavern, "DragonRoostCavern"},
        {HintRegion::ForbiddenWoods, "ForbiddenWoods"},
        {HintRegion::TowerOfTheGods, "TowerOfTheGods"},
        {HintRegion::ForsakenFortress, "ForsakenFortress"},
        {HintRegion::EarthTemple, "EarthTemple"},
        {HintRegion::WindTemple, "WindTemple"},
        {HintRegion::Hyrule, "Hyrule"},
        {HintRegion::GanonsTower, "GanonsTower"},
    };

    if (hintRegionNameMap.count(hintRegion) == 0)
    {
        return "INVALID HINT REGION";
    }
    return hintRegionNameMap.at(hintRegion);
}
