
#include "HintRegion.hpp"
#include <unordered_map>

HintRegion nameToHintRegion(const std::string& name)
{
    static std::unordered_map<std::string, HintRegion> nameHintRegionMap = {
        {"NONE", HintRegion::NONE},
        {"Mailbox", HintRegion::Mailbox},
        {"The Great Sea", HintRegion::TheGreatSea},
        {"Forsaken Fortress Sector", HintRegion::ForsakenFortressSector},
        {"Star Island", HintRegion::StarIsland},
        {"Northern Fairy Island", HintRegion::NorthernFairyIsland},
        {"Gale Isle", HintRegion::GaleIsle},
        {"Crescent Moon Island", HintRegion::CrescentMoonIsland},
        {"Seven Star Isles", HintRegion::SevenStarIsles},
        {"Overlook Island", HintRegion::OverlookIsland},
        {"Four Eye Reef", HintRegion::FourEyeReef},
        {"Mother & Child Isles", HintRegion::MotherAndChildIsles},
        {"Spectacle Island", HintRegion::SpectacleIsland},
        {"Windfall Island", HintRegion::WindfallIsland},
        {"Pawprint Isle", HintRegion::PawprintIsle},
        {"Dragon Roost Island", HintRegion::DragonRoostIsland},
        {"Flight Control Platform", HintRegion::FlightControlPlatform},
        {"Western Fairy Island", HintRegion::WesternFairyIsland},
        {"Rock Spire Isle", HintRegion::RockSpireIsle},
        {"Tingle Island", HintRegion::TingleIsland},
        {"Northern Triangle Island", HintRegion::NorthernTriangleIsland},
        {"Eastern Fairy Island", HintRegion::EasternFairyIsland},
        {"Fire Mountain", HintRegion::FireMountain},
        {"Star Belt Archipelago", HintRegion::StarBeltArchipelago},
        {"Three Eye Reef", HintRegion::ThreeEyeReef},
        {"Greatfish Isle", HintRegion::GreatfishIsle},
        {"Cyclops Reef", HintRegion::CyclopsReef},
        {"Six Eye Reef", HintRegion::SixEyeReef},
        {"Tower of the Gods Sector", HintRegion::TotGSector},
        {"Eastern Triangle Island", HintRegion::EasternTriangleIsland},
        {"Thorned Fairy Island", HintRegion::ThornedFairyIsland},
        {"Needle Rock Isle", HintRegion::NeedleRockIsle},
        {"Islet of Steel", HintRegion::IsletOfSteel},
        {"Stone Watcher Island", HintRegion::StoneWatcherIsland},
        {"Southern Triangle Island", HintRegion::SouthernTriangleIsland},
        {"Private Oasis", HintRegion::PrivateOasis},
        {"Bomb Island", HintRegion::BombIsland},
        {"Birds Peak Rock", HintRegion::BirdsPeakRock},
        {"Diamond Steppe Island", HintRegion::DiamondSteppeIsland},
        {"Five Eye Reef", HintRegion::FiveEyeReef},
        {"Shark Island", HintRegion::SharkIsland},
        {"Southern Fairy Island", HintRegion::SouthernFairyIsland},
        {"Ice Ring Isle", HintRegion::IceRingIsle},
        {"Forest Haven", HintRegion::ForestHaven},
        {"Cliff Plateau Isles", HintRegion::CliffPlateauIsles},
        {"Horseshoe Isle", HintRegion::HorseshoeIsle},
        {"Outset Island", HintRegion::OutsetIsland},
        {"Headstone Island", HintRegion::HeadstoneIsland},
        {"Two Eye Reef", HintRegion::TwoEyeReef},
        {"Angular Isles", HintRegion::AngularIsles},
        {"Boating Course", HintRegion::BoatingCourse},
        {"Five Star Isles", HintRegion::FiveStarIsles},
        {"Dragon Roost Cavern", HintRegion::DragonRoostCavern},
        {"Forbidden Woods", HintRegion::ForbiddenWoods},
        {"Tower of the Gods", HintRegion::TowerOfTheGods},
        {"Forsaken Fortress", HintRegion::ForsakenFortress},
        {"Earth Temple", HintRegion::EarthTemple},
        {"Wind Temple", HintRegion::WindTemple},
        {"Hyrule", HintRegion::Hyrule},
        {"Ganon's Tower", HintRegion::GanonsTower},
    };

    if (nameHintRegionMap.count(name) == 0)
    {
        return HintRegion::INVALID;
    }
    return nameHintRegionMap.at(name);
}

std::string hintRegionToName(const HintRegion& hintRegion)
{
    static std::unordered_map<HintRegion, std::string> hintRegionNameMap = {
        {HintRegion::NONE, "NONE"},
        {HintRegion::Mailbox, "Mailbox"},
        {HintRegion::TheGreatSea, "The Great Sea"},
        {HintRegion::ForsakenFortressSector, "Forsaken Fortress Sector"},
        {HintRegion::StarIsland, "Star Island"},
        {HintRegion::NorthernFairyIsland, "Northern Fairy Island"},
        {HintRegion::GaleIsle, "Gale Isle"},
        {HintRegion::CrescentMoonIsland, "Crescent Moon Island"},
        {HintRegion::SevenStarIsles, "Seven Star Isles"},
        {HintRegion::OverlookIsland, "Overlook Island"},
        {HintRegion::FourEyeReef, "Four Eye Reef"},
        {HintRegion::MotherAndChildIsles, "Mother & Child Isles"},
        {HintRegion::SpectacleIsland, "Spectacle Island"},
        {HintRegion::WindfallIsland, "Windfall Island"},
        {HintRegion::PawprintIsle, "Pawprint Isle"},
        {HintRegion::DragonRoostIsland, "Dragon Roost Island"},
        {HintRegion::FlightControlPlatform, "Flight Control Platform"},
        {HintRegion::WesternFairyIsland, "Western Fairy Island"},
        {HintRegion::RockSpireIsle, "Rock Spire Isle"},
        {HintRegion::TingleIsland, "Tingle Island"},
        {HintRegion::NorthernTriangleIsland, "Northern Triangle Island"},
        {HintRegion::EasternFairyIsland, "Eastern Fairy Island"},
        {HintRegion::FireMountain, "Fire Mountain"},
        {HintRegion::StarBeltArchipelago, "Star Belt Archipelago"},
        {HintRegion::ThreeEyeReef, "Three Eye Reef"},
        {HintRegion::GreatfishIsle, "Greatfish Isle"},
        {HintRegion::CyclopsReef, "Cyclops Reef"},
        {HintRegion::SixEyeReef, "Six Eye Reef"},
        {HintRegion::TotGSector, "Tower of the Gods Sector"},
        {HintRegion::EasternTriangleIsland, "Eastern Triangle Island"},
        {HintRegion::ThornedFairyIsland, "Thorned Fairy Island"},
        {HintRegion::NeedleRockIsle, "Needle Rock Isle"},
        {HintRegion::IsletOfSteel, "Islet of Steel"},
        {HintRegion::StoneWatcherIsland, "Stone Watcher Island"},
        {HintRegion::SouthernTriangleIsland, "Southern Triangle Island"},
        {HintRegion::PrivateOasis, "Private Oasis"},
        {HintRegion::BombIsland, "Bomb Island"},
        {HintRegion::BirdsPeakRock, "Birds Peak Rock"},
        {HintRegion::DiamondSteppeIsland, "Diamond Steppe Island"},
        {HintRegion::FiveEyeReef, "Five Eye Reef"},
        {HintRegion::SharkIsland, "Shark Island"},
        {HintRegion::SouthernFairyIsland, "Southern Fairy Island"},
        {HintRegion::IceRingIsle, "Ice Ring Isle"},
        {HintRegion::ForestHaven, "Forest Haven"},
        {HintRegion::CliffPlateauIsles, "Cliff Plateau Isles"},
        {HintRegion::HorseshoeIsle, "Horseshoe Isle"},
        {HintRegion::OutsetIsland, "Outset Island"},
        {HintRegion::HeadstoneIsland, "Headstone Island"},
        {HintRegion::TwoEyeReef, "Two Eye Reef"},
        {HintRegion::AngularIsles, "Angular Isles"},
        {HintRegion::BoatingCourse, "Boating Course"},
        {HintRegion::FiveStarIsles, "Five Star Isles"},
        {HintRegion::DragonRoostCavern, "Dragon Roost Cavern"},
        {HintRegion::ForbiddenWoods, "Forbidden Woods"},
        {HintRegion::TowerOfTheGods, "Tower of the Gods"},
        {HintRegion::ForsakenFortress, "Forsaken Fortress"},
        {HintRegion::EarthTemple, "Earth Temple"},
        {HintRegion::WindTemple, "Wind Temple"},
        {HintRegion::Hyrule, "Hyrule"},
        {HintRegion::GanonsTower, "Ganon's Tower"},
    };

    if (hintRegionNameMap.count(hintRegion) == 0)
    {
        return "INVALID HINT REGION";
    }
    return hintRegionNameMap.at(hintRegion);
}
