name: Run Logic Tests

on:
  - pull_request

jobs:
  run-logic-tests:
    name: Run Logic Tests
    runs-on: windows-latest

    steps:
      # Increase page size so that the compiler doesn't
      # run out of memory
      - name: Configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.4
        with:
          minimum-size: 16GB
          maximum-size: 16GB
          disk-root: "C:"

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure CMake
        working-directory: ${{ github.workspace }}
        run: cmake -G "MinGW Makefiles" -B build -DLOGIC_TESTS=True
      
      - name: Build
        working-directory: ${{ github.workspace }}
        run: cmake --build build -j

      - name: Run Tests
        working-directory: ${{ github.workspace }}/build
        run: ./wwhd_rando.exe
        